name: meetup
description: A new Flutter project.

publish_to: "none"

version: 2.4.0+7

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  basic_utils: ^4.2.2
  cached_network_image: ^3.2.1
  chat_gpt_sdk: ^2.1.8
  clipboard: ^0.1.3
  cool_alert: ^1.1.0
  dartx: ^1.1.0
  dio: ^5.1.2
  easy_onboard: ^1.0.3
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  firebase_messaging: ^14.6.2
  flag: ^6.0.0
  flex_color_scheme: ^7.1.2
  flutter:
    sdk: flutter
  flutter_downloader: ^1.10.4
  flutter_local_notifications: ^9.7.0
  flutter_localizations:
    sdk: flutter
  google_fonts: ^5.0.0
  google_mobile_ads: ^3.0.0
  google_nav_bar: ^5.0.6
  image_picker: ^0.8.7+5
  in_app_review: ^2.0.4
  jiffy: ^5.0.0
  jitsi_meet_wrapper: ^0.0.6
  line_icons: ^2.0.1
  localize_and_translate: ^4.1.1
  onboarding: ^3.1.0
  package_info_plus: ^4.0.2
  pin_code_fields: ^7.4.0
  provider: ^6.0.3
  pull_to_refresh_flutter3: ^2.0.1
  random_string: ^2.3.1
  share_plus: ^4.0.7
  shared_preferences: ^2.0.15
  singleton: ^0.0.2
  stacked: ^3.4.0
  url_launcher: ^6.1.11
  velocity_x: ^4.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.2.3
  flutter_test:
    sdk: flutter

dependency_overrides:
  http: ^0.13.0
  translator: 0.1.7

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  image: assets/images/app_icon.png
  color: "20063B"

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lang/
    - assets/
